version: "3"

services:

  keycloak:
    networks:
      - mm
    ports:
      - "8086:8080"
    container_name: keycloak
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=username
      - KEYCLOAK_PASSWORD=password

networks:
  mm:
    driver: bridge